spring:
  application:
    name: feign-server

server:
   context-path: /
   port: 9200
   display-name: feign-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/