spring:
  application:
    name: eureka-client-b

server:
   context-path: /
   port: 9991
   display-name: service-b



eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/