spring:
  application:
    name: ribbon-1

server:
   context-path: /
   port: 9200
   display-name: ribbon-server

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.110:9000/eureka/