spring:
  application:
    name: rebbon-server

server:
   context-path: /
   port: 9100
   display-name: ribbon-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/