spring:
  application:
    name: eureka-client-a

server:
   context-path: /
   port: 9990
   display-name: service-a



eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/