
#读取本地配置文件spring:
  profiles:
    active: native

  spring:
    application:
      name: config-server
    cloud:
      config:
        server:
          git:
            uri: https://github.com/xhselina/config/
            search-paths: tree/master/config-repo
            username: xhselina
            password: chadian90houer
  server:
    port: 7000

# github管理
